name = "AirspeedVelocity"
uuid = "1c8270ee-6884-45cc-9545-60fa71ec23e4"
authors = ["Miles Cranmer <miles.cranmer@gmail.com>"]
version = "1.0.0-DEV"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
